void define_fileshape(struct shapetype *shape);
void define_fourier(struct shapetype *shape, double fcoeff[2][FOURIER_TERMS]);
void define_circle(struct shapetype *c);
void define_wobblycircle(struct shapetype *shape);
void define_pointyegg(struct shapetype *egg);
void define_ellipse(struct shapetype *shape);
void define_wobbly4(struct shapetype *shape);
void define_wobbly3(struct shapetype *shape);
void define_wobbly5(struct shapetype *shape);
void define_wobblyfan3(struct shapetype *shape);
void define_ninjastar(struct shapetype *shape);
void define_pentagon(struct shapetype *shape);
void define_pentagoncircle(struct shapetype *shape);
void define_heptagoncircle(struct shapetype *shape);
void define_RichardJames_pentagon(struct shapetype *shape, double angle_D);
void define_MarjorieRice_pentagon(struct shapetype *shape, double angle_B);
void define_asymcomma(struct shapetype *shape);
void define_square(struct shapetype *sq);
void define_bowtie(struct shapetype *bowtie);
void define_zigzagbone(struct shapetype *b);
void define_bells(struct shapetype *b3);
void define_bone(struct shapetype *b4);
void define_triangle (struct shapetype *triangle);
void define_smoothedpentagon (struct shapetype *shape);
void define_hexagon (struct shapetype *shape);
void define_heptagon (struct shapetype *shape);
void define_nonagon (struct shapetype *shape);
void define_octagon (struct shapetype *shape);
/*void define_randomsmoothedoctagon (struct shapetype *shape); */
void define_smoothedoctagon (struct shapetype *shape);
void define_dodecagon (struct shapetype *shape);
void define_fan2 (struct shapetype *shape);
void define_fan3 (struct shapetype *shape);
void define_fan4 (struct shapetype *shape);
void define_flower5 (struct shapetype *shape);
void define_fan6 (struct shapetype *shape);
void define_fan12 (struct shapetype *shape);
void define_kite (struct shapetype *shape);
